// Direct Wikimedia Commons CDN thumbnail URLs (resolved once; avoids the Special:FilePath redirect).
// Regenerate if a file name changes. Keys are Commons file names without the "File:" prefix.
export const COMMONS_THUMBS: Record<string, { 640: string; 1600: string }> = {
  "(ব্লাক বেঙ্গল) বাংলাদেশী ছাগল জাতীয় পশু.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/%28%E0%A6%AC%E0%A7%8D%E0%A6%B2%E0%A6%BE%E0%A6%95_%E0%A6%AC%E0%A7%87%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A6%B2%29_%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE%E0%A6%A6%E0%A7%87%E0%A6%B6%E0%A7%80_%E0%A6%9B%E0%A6%BE%E0%A6%97%E0%A6%B2_%E0%A6%9C%E0%A6%BE%E0%A6%A4%E0%A7%80%E0%A6%AF%E0%A6%BC_%E0%A6%AA%E0%A6%B6%E0%A7%81.jpg/960px-%28%E0%A6%AC%E0%A7%8D%E0%A6%B2%E0%A6%BE%E0%A6%95_%E0%A6%AC%E0%A7%87%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A6%B2%29_%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE%E0%A6%A6%E0%A7%87%E0%A6%B6%E0%A7%80_%E0%A6%9B%E0%A6%BE%E0%A6%97%E0%A6%B2_%E0%A6%9C%E0%A6%BE%E0%A6%A4%E0%A7%80%E0%A6%AF%E0%A6%BC_%E0%A6%AA%E0%A6%B6%E0%A7%81.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/%28%E0%A6%AC%E0%A7%8D%E0%A6%B2%E0%A6%BE%E0%A6%95_%E0%A6%AC%E0%A7%87%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A6%B2%29_%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE%E0%A6%A6%E0%A7%87%E0%A6%B6%E0%A7%80_%E0%A6%9B%E0%A6%BE%E0%A6%97%E0%A6%B2_%E0%A6%9C%E0%A6%BE%E0%A6%A4%E0%A7%80%E0%A6%AF%E0%A6%BC_%E0%A6%AA%E0%A6%B6%E0%A7%81.jpg/1920px-%28%E0%A6%AC%E0%A7%8D%E0%A6%B2%E0%A6%BE%E0%A6%95_%E0%A6%AC%E0%A7%87%E0%A6%99%E0%A7%8D%E0%A6%97%E0%A6%B2%29_%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE%E0%A6%A6%E0%A7%87%E0%A6%B6%E0%A7%80_%E0%A6%9B%E0%A6%BE%E0%A6%97%E0%A6%B2_%E0%A6%9C%E0%A6%BE%E0%A6%A4%E0%A7%80%E0%A6%AF%E0%A6%BC_%E0%A6%AA%E0%A6%B6%E0%A7%81.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "2013-09-04-bushes-chicken-in-grass.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/2013-09-04-bushes-chicken-in-grass.jpg/960px-2013-09-04-bushes-chicken-in-grass.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/2013-09-04-bushes-chicken-in-grass.jpg/1920px-2013-09-04-bushes-chicken-in-grass.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "20160521-RD-LSC-0992 (27716480945).jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/20160521-RD-LSC-0992_%2827716480945%29.jpg/960px-20160521-RD-LSC-0992_%2827716480945%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/20160521-RD-LSC-0992_%2827716480945%29.jpg/1920px-20160521-RD-LSC-0992_%2827716480945%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "A farmer with his domestic ducks..jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/A_farmer_with_his_domestic_ducks..jpg/960px-A_farmer_with_his_domestic_ducks..jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/A_farmer_with_his_domestic_ducks..jpg/1920px-A_farmer_with_his_domestic_ducks..jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "A glass of milk.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/A_glass_of_milk.jpg/960px-A_glass_of_milk.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/A_glass_of_milk.jpg/1920px-A_glass_of_milk.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Aftabnagar qurbanir bajar, Badda, Dhaka, Bangladesh 2022.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Aftabnagar_qurbanir_bajar%2C_Badda%2C_Dhaka%2C_Bangladesh_2022.jpg/960px-Aftabnagar_qurbanir_bajar%2C_Badda%2C_Dhaka%2C_Bangladesh_2022.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Aftabnagar_qurbanir_bajar%2C_Badda%2C_Dhaka%2C_Bangladesh_2022.jpg/1920px-Aftabnagar_qurbanir_bajar%2C_Badda%2C_Dhaka%2C_Bangladesh_2022.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Back-yard summer tilapia pond, tilapia and goldfish fry.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Back-yard_summer_tilapia_pond%2C_tilapia_and_goldfish_fry.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled", 1600: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Back-yard_summer_tilapia_pond%2C_tilapia_and_goldfish_fry.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
  "Bangladeshi Fish04.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Bangladeshi_Fish04.jpg/960px-Bangladeshi_Fish04.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Bangladeshi_Fish04.jpg/1920px-Bangladeshi_Fish04.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Basa fish - Vinh Long Market.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Basa_fish_-_Vinh_Long_Market.jpg/960px-Basa_fish_-_Vinh_Long_Market.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Basa_fish_-_Vinh_Long_Market.jpg/1920px-Basa_fish_-_Vinh_Long_Market.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Catla fish displayed for sale at Boiddar Bazar, Sonargaon.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Catla_fish_displayed_for_sale_at_Boiddar_Bazar%2C_Sonargaon.jpg/960px-Catla_fish_displayed_for_sale_at_Boiddar_Bazar%2C_Sonargaon.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Catla_fish_displayed_for_sale_at_Boiddar_Bazar%2C_Sonargaon.jpg/1920px-Catla_fish_displayed_for_sale_at_Boiddar_Bazar%2C_Sonargaon.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Chicken eggs in tray.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Chicken_eggs_in_tray.jpg/960px-Chicken_eggs_in_tray.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Chicken_eggs_in_tray.jpg/1920px-Chicken_eggs_in_tray.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Eggs in basket 2020 G1.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Eggs_in_basket_2020_G1.jpg/960px-Eggs_in_basket_2020_G1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Eggs_in_basket_2020_G1.jpg/1920px-Eggs_in_basket_2020_G1.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Labeo rohita.JPG": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Labeo_rohita.JPG/960px-Labeo_rohita.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Labeo_rohita.JPG/1920px-Labeo_rohita.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Rice bran.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Rice_bran.jpg/960px-Rice_bran.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Rice_bran.jpg/1920px-Rice_bran.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Sahiwal -breed cow at a dairy unit attached to Bhai Ram Singh Memorial Place, Bhaini Sahib,in district Ludhyana ,Punjab India.JPG": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Sahiwal_-breed_cow_at_a_dairy_unit_attached_to_Bhai_Ram_Singh_Memorial_Place%2C_Bhaini_Sahib%2Cin_district_Ludhyana_%2CPunjab_India.JPG/960px-Sahiwal_-breed_cow_at_a_dairy_unit_attached_to_Bhai_Ram_Singh_Memorial_Place%2C_Bhaini_Sahib%2Cin_district_Ludhyana_%2CPunjab_India.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Sahiwal_-breed_cow_at_a_dairy_unit_attached_to_Bhai_Ram_Singh_Memorial_Place%2C_Bhaini_Sahib%2Cin_district_Ludhyana_%2CPunjab_India.JPG/1920px-Sahiwal_-breed_cow_at_a_dairy_unit_attached_to_Bhai_Ram_Singh_Memorial_Place%2C_Bhaini_Sahib%2Cin_district_Ludhyana_%2CPunjab_India.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Vatch pla nin.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Vatch_pla_nin.jpg/960px-Vatch_pla_nin.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Vatch_pla_nin.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled" },
  "Milk loading.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Milk_loading.jpg/960px-Milk_loading.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Milk_loading.jpg/1920px-Milk_loading.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Duck Egg.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Duck_Egg.jpg/960px-Duck_Egg.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Duck_Egg.jpg/1920px-Duck_Egg.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail" },
  "Duck Eggs.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Duck_Eggs.jpg/960px-Duck_Eggs.jpg", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Duck_Eggs.jpg/1920px-Duck_Eggs.jpg" },
  "Buffalo, Kaloipur, chapainababagonj, Bangladesh.jpg": { 640: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Buffalo%2C_Kaloipur%2C_chapainababagonj%2C_Bangladesh.jpg/960px-Buffalo%2C_Kaloipur%2C_chapainababagonj%2C_Bangladesh.jpg", 1600: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Buffalo%2C_Kaloipur%2C_chapainababagonj%2C_Bangladesh.jpg/1920px-Buffalo%2C_Kaloipur%2C_chapainababagonj%2C_Bangladesh.jpg" },
}
